// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.services;

public interface EmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.EmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
